from __future__ import division, print_function
import re
import itertools

def words(text): return set(text.split())

"""See the README for explanations/results."""

from collections import defaultdict
def regex_components(winners, losers):
    ...
    pairs = {p for w in winners for p in paaairs(w) if not matches(p, losers)}
    return pairs

def paaairs(w):
    return {w[i]+'.'+q+b for i in range(len(w)) for b in w[i+1:] for q in '*+?'}

# Pre-compiling the regex components speeds things up a little:

def matches(regex, strings):
    "Return a set of all the strings that are matched by regex."
    r = re.compile(regex)
    return {s for s in strings if r.search(s)}


def findregex(winners, losers):
    """"Find a regex that matches all winners but no losers (sets of strings)."""

    def search(regex, covers):
        """Recursively build a shortest regex from the components."""

        # Simplify: Throw away useless components and handle forced decisions.
        previous = None
        while covers != previous:
            previous = covers

            # Only keep a set of superior components (throw away those that cover
            # a subset of a superior component and aren't shorter).
            COVERS = {}
            for c in sorted(covers, key=lambda c:(-len(covers[c]), len(c))):
                ws = covers[c]
                if ws and not any(ws<=WS and len(c)>=len(C) for C,WS in COVERS.items()):
                    COVERS[c] = ws
            covers = COVERS

            # For winners covered only by one component, use those needed components now.
            coverers = defaultdict(list)
            for c, ws in covers.items():
                for w in ws:
                    coverers[w].append(c)
            needed = {cs[0] for cs in coverers.values() if len(cs) == 1}
            if needed:
                regex += '|' + '|'.join(needed)
                covered = {w for c in needed for w in covers[c]}
                covers = {c:ws-covered for c,ws in covers.items() if c not in needed}

        # Nothing left to do? Then update the answer.
        if not covers:
            if len(regex) < len(answer[0]):
                answer[0] = regex
            return

        # Stop when already too bad
        if len(regex)+1+min(len(c) for c in covers) >= len(answer[0]):
            return

        # Try with and without the component looking best
        best = max(covers, key=lambda c: 3 * len(covers[c]) - len(c))
        search(regex + '|' + best, {c:ws-covers[best] for c,ws in covers.items()})
        covers.pop(best)
        search(regex, covers)

    # Setup, search, answer
    answer = ['|'.join('^'+w+'$' for w in winners)]
    search('', {c:matches(c, winners) for c in regex_components(winners, losers)})
    return answer[0][1:]

winners = words('''RNBKRNQB RNBKRBNQ RNBKRBQN RNBKQRNB RNBKQNRB RNBKQBRN RNBKQBNR RNBQKBNR RNQNBBKR RNQKBNRB RBBKRNNQ RBKRNQBN RBKRBNQN RBKRBQNN RBQKBNRN RKRNNQBB RKRNBQNB RKRBNQBN RKRBBQNN RKRBQNBN RKBRNQNB RKBNRQNB RKBNNQRB RKBBRQNN RKBBNQRN RKBBNQNR RQNNBKRB RQNBBKRN RQKBNRBN NRNBKRBQ NRNBKQBR NRBKRBNQ NRBQKBNR NRKRBNQB NRKRBBQN NRKBBRQN NRKBBNQR NRQNBBKR NRQKBNRB NNRKRBBQ NNRKBBRQ NNQRBBKR NNQBRKBR NNQBBRKR NBRNBKQR NBRKRNBQ NBRKRQBN NBRKNQBR NBRKBRNQ NBRKBNRQ NBRKBQRN NBRKBQNR NBNQBRKR NBQNRKBR NBQNBRKR NQRNBKRB NQRBBKRN NQNRBKRB NQNBRKBR NQBRKBNR NQBNRKRB NQBBRKRN BRNBKQRN BRNBKQNR BRNQKBNR BRKRNNQB BRKRNBQN BRKBRNQN BRKBNRQN BRKBNNQR BRQNNBKR BNRKRBNQ BNRQKBNR BNQRNBKR BNQNRBKR BNQBNRKR BBRKRNNQ BBQNNRKR BQNRKBNR BQNNRKRB BQNBRKRN QRNBKRBN QRBBKRNN QNRBKRBN QNNRKRBB QNNRKBBR QNBRKRNB QNBRKBRN QNBRKBNR QBRKBNRN QBNRKRBN QBBRKRNN''')

losers = words('''RNNBBKRQ RNNBBKQR RNNBBQKR RNNBKRBQ RNNBKQBR RNNBQKBR RNNKRBBQ RNNKRQBB RNNKBRQB RNNKBBRQ RNNKBBQR RNNKBQRB RNNKQRBB RNNKQBBR RNNQBBKR RNNQBKRB RNNQKRBB RNNQKBBR RNBNKRQB RNBNKBRQ RNBNKBQR RNBNKQRB RNBNQBKR RNBNQKRB RNBBNKRQ RNBBNKQR RNBBNQKR RNBBKRNQ RNBBKRQN RNBBKNRQ RNBBKNQR RNBBKQRN RNBBKQNR RNBBQNKR RNBBQKRN RNBBQKNR RNBKRQNB RNBKNRQB RNBKNBRQ RNBKNBQR RNBKNQRB RNBQNBKR RNBQNKRB RNBQKRNB RNBQKNRB RNBQKBRN RNKRNBBQ RNKRNQBB RNKRBNQB RNKRBBNQ RNKRBBQN RNKRBQNB RNKRQNBB RNKRQBBN RNKNRBBQ RNKNRQBB RNKNBRQB RNKNBBRQ RNKNBBQR RNKNBQRB RNKNQRBB RNKNQBBR RNKBRNBQ RNKBRQBN RNKBNRBQ RNKBNQBR RNKBBRNQ RNKBBRQN RNKBBNRQ RNKBBNQR RNKBBQRN RNKBBQNR RNKBQRBN RNKBQNBR RNKQRNBB RNKQRBBN RNKQNRBB RNKQNBBR RNKQBRNB RNKQBNRB RNKQBBRN RNKQBBNR RNQNBKRB RNQNKRBB RNQNKBBR RNQBNKBR RNQBBNKR RNQBBKRN RNQBBKNR RNQBKRBN RNQBKNBR RNQKRNBB RNQKRBBN RNQKNRBB RNQKNBBR RNQKBRNB RNQKBBRN RNQKBBNR RBNNBKRQ RBNNBKQR RBNNBQKR RBNNKRBQ RBNNKQBR RBNNQKBR RBNKRNBQ RBNKRQBN RBNKNRBQ RBNKNQBR RBNKBRNQ RBNKBRQN RBNKBNRQ RBNKBNQR RBNKBQRN RBNKBQNR RBNKQRBN RBNKQNBR RBNQNKBR RBNQBNKR RBNQBKRN RBNQBKNR RBNQKRBN RBNQKNBR RBBNNKRQ RBBNNKQR RBBNNQKR RBBNKRNQ RBBNKRQN RBBNKNRQ RBBNKNQR RBBNKQRN RBBNKQNR RBBNQNKR RBBNQKRN RBBNQKNR RBBKRNQN RBBKRQNN RBBKNRNQ RBBKNRQN RBBKNNRQ RBBKNNQR RBBKNQRN RBBKNQNR RBBKQRNN RBBKQNRN RBBKQNNR RBBQNNKR RBBQNKRN RBBQNKNR RBBQKRNN RBBQKNRN RBBQKNNR RBKRNNBQ RBKRBNNQ RBKRQNBN RBKNRNBQ RBKNRQBN RBKNNRBQ RBKNNQBR RBKNBRNQ RBKNBRQN RBKNBNRQ RBKNBNQR RBKNBQRN RBKNBQNR RBKNQRBN RBKNQNBR RBKQRNBN RBKQNRBN RBKQNNBR RBKQBRNN RBKQBNRN RBKQBNNR RBQNNKBR RBQNBNKR RBQNBKRN RBQNBKNR RBQNKRBN RBQNKNBR RBQKRNBN RBQKNRBN RBQKNNBR RBQKBRNN RBQKBNNR RKRNNBBQ RKRNBNQB RKRNBBNQ RKRNBBQN RKRNQNBB RKRNQBBN RKRBNNBQ RKRBBNNQ RKRBBNQN RKRQNNBB RKRQNBBN RKRQBNNB RKRQBBNN RKNRNBBQ RKNRNQBB RKNRBNQB RKNRBBNQ RKNRBBQN RKNRBQNB RKNRQNBB RKNRQBBN RKNNRBBQ RKNNRQBB RKNNBRQB RKNNBBRQ RKNNBBQR RKNNBQRB RKNNQRBB RKNNQBBR RKNBRNBQ RKNBRQBN RKNBNRBQ RKNBNQBR RKNBBRNQ RKNBBRQN RKNBBNRQ RKNBBNQR RKNBBQRN RKNBBQNR RKNBQRBN RKNBQNBR RKNQRNBB RKNQRBBN RKNQNRBB RKNQNBBR RKNQBRNB RKNQBNRB RKNQBBRN RKNQBBNR RKBRNNQB RKBRNBNQ RKBRNBQN RKBRQNNB RKBRQBNN RKBNRNQB RKBNRBNQ RKBNRBQN RKBNNRQB RKBNNBRQ RKBNNBQR RKBNQRNB RKBNQNRB RKBNQBRN RKBNQBNR RKBBRNNQ RKBBRNQN RKBBNRNQ RKBBNRQN RKBBNNRQ RKBBNNQR RKBBQRNN RKBBQNRN RKBBQNNR RKBQRNNB RKBQRBNN RKBQNRNB RKBQNNRB RKBQNBRN RKBQNBNR RKQRNNBB RKQRNBBN RKQRBNNB RKQRBBNN RKQNRNBB RKQNRBBN RKQNNRBB RKQNNBBR RKQNBRNB RKQNBNRB RKQNBBRN RKQNBBNR RKQBRNBN RKQBNRBN RKQBNNBR RKQBBRNN RKQBBNRN RKQBBNNR RQNNBBKR RQNNKRBB RQNNKBBR RQNBNKBR RQNBBNKR RQNBBKNR RQNBKRBN RQNBKNBR RQNKRNBB RQNKRBBN RQNKNRBB RQNKNBBR RQNKBRNB RQNKBNRB RQNKBBRN RQNKBBNR RQBNNBKR RQBNNKRB RQBNKRNB RQBNKNRB RQBNKBRN RQBNKBNR RQBBNNKR RQBBNKRN RQBBNKNR RQBBKRNN RQBBKNRN RQBBKNNR RQBKRNNB RQBKRBNN RQBKNRNB RQBKNNRB RQBKNBRN RQBKNBNR RQKRNNBB RQKRNBBN RQKRBNNB RQKRBBNN RQKNRNBB RQKNRBBN RQKNNRBB RQKNNBBR RQKNBRNB RQKNBNRB RQKNBBRN RQKNBBNR RQKBRNBN RQKBNNBR RQKBBRNN RQKBBNRN RQKBBNNR NRNBBKRQ NRNBBKQR NRNBBQKR NRNBQKBR NRNKRBBQ NRNKRQBB NRNKBRQB NRNKBBRQ NRNKBBQR NRNKBQRB NRNKQRBB NRNKQBBR NRNQBBKR NRNQBKRB NRNQKRBB NRNQKBBR NRBNKRQB NRBNKBRQ NRBNKBQR NRBNKQRB NRBNQBKR NRBNQKRB NRBBNKRQ NRBBNKQR NRBBNQKR NRBBKRNQ NRBBKRQN NRBBKNRQ NRBBKNQR NRBBKQRN NRBBKQNR NRBBQNKR NRBBQKRN NRBBQKNR NRBKRNQB NRBKRBQN NRBKRQNB NRBKNRQB NRBKNBRQ NRBKNBQR NRBKNQRB NRBKQRNB NRBKQNRB NRBKQBRN NRBKQBNR NRBQNBKR NRBQNKRB NRBQKRNB NRBQKNRB NRBQKBRN NRKRNBBQ NRKRNQBB NRKRBBNQ NRKRBQNB NRKRQNBB NRKRQBBN NRKNRBBQ NRKNRQBB NRKNBRQB NRKNBBRQ NRKNBBQR NRKNBQRB NRKNQRBB NRKNQBBR NRKBRNBQ NRKBRQBN NRKBNRBQ NRKBNQBR NRKBBRNQ NRKBBNRQ NRKBBQRN NRKBBQNR NRKBQRBN NRKBQNBR NRKQRNBB NRKQRBBN NRKQNRBB NRKQNBBR NRKQBRNB NRKQBNRB NRKQBBRN NRKQBBNR NRQNBKRB NRQNKRBB NRQNKBBR NRQBNKBR NRQBBNKR NRQBBKRN NRQBBKNR NRQBKRBN NRQBKNBR NRQKRNBB NRQKRBBN NRQKNRBB NRQKNBBR NRQKBRNB NRQKBBRN NRQKBBNR NNRBBKRQ NNRBBKQR NNRBBQKR NNRBKRBQ NNRBKQBR NNRBQKBR NNRKRQBB NNRKBRQB NNRKBBQR NNRKBQRB NNRKQRBB NNRKQBBR NNRQBBKR NNRQBKRB NNRQKRBB NNRQKBBR NNBRKRQB NNBRKBRQ NNBRKBQR NNBRKQRB NNBRQBKR NNBRQKRB NNBBRKRQ NNBBRKQR NNBBRQKR NNBBQRKR NNBQRBKR NNBQRKRB NNQRBKRB NNQRKRBB NNQRKBBR NBRNBKRQ NBRNBQKR NBRNKRBQ NBRNKQBR NBRNQKBR NBRKNRBQ NBRKBRQN NBRKBNQR NBRKQRBN NBRKQNBR NBRQNKBR NBRQBNKR NBRQBKRN NBRQBKNR NBRQKRBN NBRQKNBR NBNRBKRQ NBNRBKQR NBNRBQKR NBNRKRBQ NBNRKQBR NBNRQKBR NBNQRKBR NBBRNKRQ NBBRNKQR NBBRNQKR NBBRKRNQ NBBRKRQN NBBRKNRQ NBBRKNQR NBBRKQRN NBBRKQNR NBBRQNKR NBBRQKRN NBBRQKNR NBBNRKRQ NBBNRKQR NBBNRQKR NBBNQRKR NBBQRNKR NBBQRKRN NBBQRKNR NBBQNRKR NBQRNKBR NBQRBNKR NBQRBKRN NBQRBKNR NBQRKRBN NBQRKNBR NQRNBBKR NQRNKRBB NQRNKBBR NQRBNKBR NQRBBNKR NQRBBKNR NQRBKRBN NQRBKNBR NQRKRNBB NQRKRBBN NQRKNRBB NQRKNBBR NQRKBRNB NQRKBNRB NQRKBBRN NQRKBBNR NQNRBBKR NQNRKRBB NQNRKBBR NQNBBRKR NQBRNBKR NQBRNKRB NQBRKRNB NQBRKNRB NQBRKBRN NQBNRBKR NQBBRNKR NQBBRKNR NQBBNRKR BRNNKRQB BRNNKBRQ BRNNKBQR BRNNKQRB BRNNQBKR BRNNQKRB BRNBNKRQ BRNBNKQR BRNBNQKR BRNBKRNQ BRNBKRQN BRNBKNRQ BRNBKNQR BRNBQNKR BRNBQKRN BRNBQKNR BRNKRNQB BRNKRBNQ BRNKRBQN BRNKRQNB BRNKNRQB BRNKNBRQ BRNKNBQR BRNKNQRB BRNKQRNB BRNKQNRB BRNKQBRN BRNKQBNR BRNQNBKR BRNQNKRB BRNQKRNB BRNQKNRB BRNQKBRN BRKRNBNQ BRKRNQNB BRKRQNNB BRKRQBNN BRKNRNQB BRKNRBNQ BRKNRBQN BRKNRQNB BRKNNRQB BRKNNBRQ BRKNNBQR BRKNNQRB BRKNQRNB BRKNQNRB BRKNQBRN BRKNQBNR BRKBRNNQ BRKBRQNN BRKBNRNQ BRKBNNRQ BRKBNQRN BRKBNQNR BRKBQRNN BRKBQNRN BRKBQNNR BRKQRNNB BRKQRBNN BRKQNRNB BRKQNNRB BRKQNBRN BRKQNBNR BRQNNKRB BRQNKRNB BRQNKNRB BRQNKBRN BRQNKBNR BRQBNNKR BRQBNKRN BRQBNKNR BRQBKRNN BRQBKNRN BRQBKNNR BRQKRNNB BRQKRBNN BRQKNRNB BRQKNNRB BRQKNBRN BRQKNBNR BNRNKRQB BNRNKBRQ BNRNKBQR BNRNKQRB BNRNQBKR BNRNQKRB BNRBNKRQ BNRBNKQR BNRBNQKR BNRBKRNQ BNRBKRQN BNRBKNRQ BNRBKNQR BNRBKQRN BNRBKQNR BNRBQNKR BNRBQKRN BNRBQKNR BNRKRNQB BNRKRBQN BNRKRQNB BNRKNRQB BNRKNBRQ BNRKNBQR BNRKNQRB BNRKQRNB BNRKQNRB BNRKQBRN BNRKQBNR BNRQNBKR BNRQNKRB BNRQKRNB BNRQKNRB BNRQKBRN BNNRKRQB BNNRKBRQ BNNRKBQR BNNRKQRB BNNRQBKR BNNRQKRB BNNBRKRQ BNNBRKQR BNNBRQKR BNNBQRKR BNNQRBKR BNNQRKRB BNQRNKRB BNQRKRNB BNQRKNRB BNQRKBRN BNQRKBNR BNQNRKRB BNQBRNKR BNQBRKRN BNQBRKNR BBRNNKRQ BBRNNKQR BBRNNQKR BBRNKRNQ BBRNKRQN BBRNKNRQ BBRNKNQR BBRNKQRN BBRNKQNR BBRNQNKR BBRNQKRN BBRNQKNR BBRKRNQN BBRKRQNN BBRKNRNQ BBRKNRQN BBRKNNRQ BBRKNNQR BBRKNQRN BBRKNQNR BBRKQRNN BBRKQNRN BBRKQNNR BBRQNNKR BBRQNKRN BBRQNKNR BBRQKRNN BBRQKNRN BBRQKNNR BBNRNKRQ BBNRNKQR BBNRNQKR BBNRKRNQ BBNRKRQN BBNRKNRQ BBNRKNQR BBNRKQRN BBNRKQNR BBNRQNKR BBNRQKRN BBNRQKNR BBNNRKRQ BBNNRKQR BBNNRQKR BBNNQRKR BBNQRNKR BBNQRKRN BBNQRKNR BBNQNRKR BBQRNNKR BBQRNKRN BBQRNKNR BBQRKRNN BBQRKNRN BBQRKNNR BBQNRNKR BBQNRKRN BBQNRKNR BQRNNBKR BQRNNKRB BQRNKRNB BQRNKNRB BQRNKBRN BQRNKBNR BQRBNNKR BQRBNKRN BQRBNKNR BQRBKRNN BQRBKNRN BQRBKNNR BQRKRNNB BQRKRBNN BQRKNRNB BQRKNNRB BQRKNBRN BQRKNBNR BQNRNBKR BQNRNKRB BQNRKRNB BQNRKNRB BQNRKBRN BQNNRBKR BQNBRNKR BQNBRKNR BQNBNRKR QRNNBBKR QRNNBKRB QRNNKRBB QRNNKBBR QRNBNKBR QRNBBNKR QRNBBKRN QRNBBKNR QRNBKNBR QRNKRNBB QRNKRBBN QRNKNRBB QRNKNBBR QRNKBRNB QRNKBNRB QRNKBBRN QRNKBBNR QRBNNBKR QRBNNKRB QRBNKRNB QRBNKNRB QRBNKBRN QRBNKBNR QRBBNNKR QRBBNKRN QRBBNKNR QRBBKNRN QRBBKNNR QRBKRNNB QRBKRBNN QRBKNRNB QRBKNNRB QRBKNBRN QRBKNBNR QRKRNNBB QRKRNBBN QRKRBNNB QRKRBBNN QRKNRNBB QRKNRBBN QRKNNRBB QRKNNBBR QRKNBRNB QRKNBNRB QRKNBBRN QRKNBBNR QRKBRNBN QRKBNRBN QRKBNNBR QRKBBRNN QRKBBNRN QRKBBNNR QNRNBBKR QNRNBKRB QNRNKRBB QNRNKBBR QNRBNKBR QNRBBNKR QNRBBKRN QNRBBKNR QNRBKNBR QNRKRNBB QNRKRBBN QNRKNRBB QNRKNBBR QNRKBRNB QNRKBNRB QNRKBBRN QNRKBBNR QNNRBBKR QNNRBKRB QNNBRKBR QNNBBRKR QNBRNBKR QNBRNKRB QNBRKNRB QNBNRBKR QNBNRKRB QNBBRNKR QNBBRKRN QNBBRKNR QNBBNRKR QBRNNKBR QBRNBNKR QBRNBKRN QBRNBKNR QBRNKRBN QBRNKNBR QBRKRNBN QBRKNRBN QBRKNNBR QBRKBRNN QBRKBNNR QBNRNKBR QBNRBNKR QBNRBKRN QBNRBKNR QBNRKNBR QBNNRKBR QBNNBRKR QBBRNNKR QBBRNKRN QBBRNKNR QBBRKNRN QBBRKNNR QBBNRNKR QBBNRKRN QBBNRKNR QBBNNRKR''')


print(findregex(winners, losers))
print("Hello")
